### PR TITLE
Some documentation added.

### PR DESCRIPTION
**Pull request by AliceFord**
Hi Sory-Noroc, this was mainly a commit to increase the documentation of the functions in the code in your repositories. As well as this, I wanted to say well done for programming at such a young age, and also I wish to ask how you found me? I found you on fiverr a few weeks ago, however I don't believe I said anything. It doesn't really matter though, I could just be being silly and of contacted you already. I wish there were a messaging feature on github!

### CODE REVIEW

**Comment by Sory-Noroc** [comment]
Hello. Thanks for your support, sir. I don't remember you from fiverr, but
would like to help you if you will need me. :) Have a nice week!

-Sory


Dum, 10 ian. 2021, 22:54 TechieHelper <notifications@github.com> a scris:

**Comment by AliceFord** [comment]
Ok thanks :) Can you merge my pull?

**Comment by Sory-Noroc** [comment]
Done. May I know why the merge is so important to you? :D

În lun., 11 ian. 2021 la 10:08, TechieHelper <notifications@github.com> a
scris:

**Comment by AliceFord** [comment]
Oh no I just thought that you might of forgotten about it lol

**Pull request merged**
